services:
  postgres-nexus:
    image: postgres:18.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nexus_writer
      POSTGRES_USER: nexus_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_nexus_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexus_user -d nexus_writer"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - nexus-network

  nexus-writer:
    build: .
    ports:
      - 8000:8000
    command: >
      sh -c "uv run aerich upgrade && uv run uvicorn main:app --host 0.0.0.0 --port 8000"
    env_file: .env
    environment:
      DATABASE_URL: asyncpg://nexus_user:password@postgres-nexus:5432/nexus_writer
    depends_on:
      postgres-nexus:
        condition: service_healthy
    networks:
      - nexus-network

networks:
  nexus-network:
    driver: bridge

volumes:
  postgres_nexus_data: