"""removed depracated field

Revision ID: 13a669dca120
Revises: 2bb4ee74b95d
Create Date: 2025-12-06 12:25:20.087213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '13a669dca120'
down_revision: Union[str, None] = '2bb4ee74b95d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'chapter_context')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('chapter_context', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
