"""Added JSONB Fields

Revision ID: 2bb4ee74b95d
Revises: 6b479bfb7c2c
Create Date: 2025-12-03 11:41:41.783020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bb4ee74b95d'
down_revision: Union[str, None] = '6b479bfb7c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('word_count', sa.Integer(), nullable=False))
    op.add_column('chapter', sa.Column('last_extracted_word_count', sa.Integer(), nullable=True))
    op.add_column('chapter', sa.Column('condensed_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chapter', sa.Column('timeline_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chapter', sa.Column('themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chapter', sa.Column('emotional_arc', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chapter', sa.Column('character_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chapter', sa.Column('plot_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chapter', sa.Column('world_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chapter', sa.Column('structure_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chapter', sa.Column('line_edits', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chapter', sa.Column('line_edits_generated_at', sa.DateTime(), nullable=True))
    op.add_column('chapter', sa.Column('last_extracted_at', sa.DateTime(), nullable=True))
    op.add_column('chapter', sa.Column('extraction_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chapter', sa.Column('chapter_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('story', sa.Column('story_context', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'story_context')
    op.drop_column('chapter', 'chapter_context')
    op.drop_column('chapter', 'extraction_version')
    op.drop_column('chapter', 'last_extracted_at')
    op.drop_column('chapter', 'line_edits_generated_at')
    op.drop_column('chapter', 'line_edits')
    op.drop_column('chapter', 'structure_extraction')
    op.drop_column('chapter', 'world_extraction')
    op.drop_column('chapter', 'plot_extraction')
    op.drop_column('chapter', 'character_extraction')
    op.drop_column('chapter', 'emotional_arc')
    op.drop_column('chapter', 'themes')
    op.drop_column('chapter', 'timeline_context')
    op.drop_column('chapter', 'condensed_context')
    op.drop_column('chapter', 'last_extracted_word_count')
    op.drop_column('chapter', 'word_count')
    # ### end Alembic commands ###
