"""removed on delete cascades for chapter pointers

Revision ID: 75a00b324ef5
Revises: f1d454fb6fc5
Create Date: 2025-07-13 20:30:08.079392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '75a00b324ef5'
down_revision: Union[str, None] = 'f1d454fb6fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chapter_next_chapter_id_fkey'), 'chapter', type_='foreignkey')
    op.drop_constraint(op.f('chapter_prev_chapter_id_fkey'), 'chapter', type_='foreignkey')
    op.create_foreign_key(None, 'chapter', 'chapter', ['next_chapter_id'], ['id'])
    op.create_foreign_key(None, 'chapter', 'chapter', ['prev_chapter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.create_foreign_key(op.f('chapter_prev_chapter_id_fkey'), 'chapter', 'chapter', ['prev_chapter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('chapter_next_chapter_id_fkey'), 'chapter', 'chapter', ['next_chapter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
