"""more jsonb madness!

Revision ID: aa7ae50525f0
Revises: 13a669dca120
Create Date: 2025-12-11 23:53:49.867259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa7ae50525f0'
down_revision: Union[str, None] = '13a669dca120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('character_bios', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('story', sa.Column('plot_threads', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'plot_threads')
    op.drop_column('story', 'character_bios')
    # ### end Alembic commands ###
