"""made story context nullable

Revision ID: b8441ae972e5
Revises: fddefaff7f20
Create Date: 2025-12-24 10:16:22.835485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b8441ae972e5'
down_revision: Union[str, None] = 'fddefaff7f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('story', 'story_context',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('story', 'story_context',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
