"""New pointers to prev and next chapter

Revision ID: caf9edf28584
Revises: c696ba338efe
Create Date: 2025-06-05 14:48:23.406043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'caf9edf28584'
down_revision: Union[str, None] = 'c696ba338efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('next_chapter_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chapter', sa.Column('prev_chapter_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'chapter', 'chapter', ['next_chapter_id'], ['id'])
    op.create_foreign_key(None, 'chapter', 'chapter', ['prev_chapter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.drop_column('chapter', 'prev_chapter_id')
    op.drop_column('chapter', 'next_chapter_id')
    # ### end Alembic commands ###
